### PR TITLE
fix(deps): bump google.golang.org/protobuf from 1.30.0 to 1.33.0 in /components/{odh-}notebook-controller

### PR DESCRIPTION
**Pull request by jiridanek**
## Description

* https://github.com/jiridanek/kubeflow/pull/1
* https://github.com/jiridanek/kubeflow/pull/2

## How Has This Been Tested?

TODO

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by rkpattnaik780 — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
Apologies for missing this.
Is this still relevant for PR ? @jiridanek

**Comment by jiridanek** [comment]
@harshad16 it is still being reported as vulnerability; it might be best to do a single PR with dependency updates combined, so that I can test it all at once. Should we try to get this into 2.11 or 2.12 is fine?

I think 2.12 would be better. There is also the x/net lib to update, and I am sure that there will be more.

**Comment by jiridanek** [comment]
govulncheck is not complaining about protobuf, so let's not do this, at least not now

**Pull request closed without merging**
