### PR TITLE
Update ODH kubeflow maintainer list

### PR DESCRIPTION
**Pull request by harshad16**
Update ODH kubeflow maintainer list

### CODE REVIEW

**Comment by harshad16** [comment]
@jiridanek would you like to join the odh org ?

**Comment by jiridanek** [comment]
> @jiridanek would you like to join the odh org ?

Yes, thanks. I would!

**Review by atheo89 — APPROVED** [review]
/lgtm

**Comment by atheo89** [comment]
@jiridanek You need to be added on the opendatahub-io org

**Comment by jiridanek** [comment]
@jstourac, you too

**Pull request merged**
