### PR TITLE
[stable] Fix naming of the helper.go file so it follows the golang conventions

### PR DESCRIPTION
**Pull request by jstourac**
https://issues.redhat.com/browse/RHOAIENG-11259

This name caused go vulnerability check to fail since this file is part
of the tests and relevant other test files weren't compiled because they
have their _test inffix as expected.

Note: this is also alignment to what is in v1.7-branch already.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
Okay, so we can see all is green now. I'm gonna remove the CVE fix commit from this PR now, which will be introduced by the #378 anyway.

**Review by jiridanek — APPROVED** [review]

**Comment by harshad16** [comment]
Thanks for fix
/approve

**Comment by harshad16** [comment]
Error seems to be for the x/net , which are fixed in #378

**Comment by harshad16** [comment]
Thank you for rebasing 
/lgtm
/approve

**Comment by jiridanek** [comment]
> I guess that another approve via GH UI needs to be done.

By harshad, andriana, or adriel, our approves don't count there

**Comment by harshad16** [comment]
>By harshad, andriana, or adriel, our approves don't count there

I think @jiridanek , prow is considering approver from all the people in approvers list.
see this: 
Screenshot from 2024-08-13 09-46-57

**Comment by jstourac** [comment]
> > By harshad, andriana, or adriel, our approves don't count there
> 
> I think @jiridanek , prow is considering approver from all the people in approvers list. see this: Screenshot from 2024-08-13 09-46-57

Hm, but here it looks like it truly waits for the UI approve which needs to be done by the people set in the repo settings, not in the owners?

**Comment by harshad16** [comment]
>but here it looks like it truly waits for the UI approve which needs to be done by the people set in the repo settings, not in the owners?

@jstourac , i didn't get that completely
can you explain me a little more?

**Review by harshad16 — APPROVED** [review]

**Comment by jstourac** [comment]
> > but here it looks like it truly waits for the UI approve which needs to be done by the people set in the repo settings, not in the owners?
> 
> @jstourac , i didn't get that completely can you explain me a little more?

I mean, it looks that the settings of this repository waits first to have two approvers that are done via GitHub UI, not via `/approve` command. Only then this PR is marked as possible to merge. And this approve must be done by only a couple of people that are set in the repository settings, irrelevant to values in the OWNERS file in the repository. Which is basically people that Jiri mentioned above.

I'm not expert in this, I'm usually lost in our repository settings WRT merging bots, so I can be wrong. But as you can see, once you approved, there is 1 approval shown at the end of this page. I suppose once there are 2, this can be moved further. :slightly_smiling_face:

**Comment by atheo89** [comment]
Thanks Jan! 

/lgtm
/approve

**Comment by jiridanek** [comment]
But we met the GitHub merge criteria, now anyone with write access to the repository can merge this, as the last line says

**Comment by jiridanek** [comment]
image

**Comment by jstourac** [comment]
So openshift/release#55570 is merged. Let's see whether this will be grabbed automatically somehow now... :face_with_diagonal_mouth:

**Pull request merged**
