### PR TITLE
Fix wrong imports in tests on stable branch caused by cherry-picking mistakes

### PR DESCRIPTION
**Pull request by jiridanek**
This has been introduced when cherry-picking https://github.com/opendatahub-io/kubeflow/pull/250/files#r1563972573 to stable

## Description

* https://github.com/opendatahub-io/kubeflow/pull/241/files#diff-f43e081bcb07c8eb52ef6e4aeee0a508e129f48b0268f4b95e6c268ec9cdf648L23

## How Has This Been Tested?
GitHub Actions now pass

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by rkpattnaik780 — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
/lgtm
/approve

thanks for the work :100:

**Comment by jiridanek** [comment]
@harshad16 looks like this won't automerge

>  tide Pending — Not mergeable. No Tide query for branch stable found.

**Pull request merged**
