### PR TITLE
Sync `main` into `v1.9-branch`

### PR DESCRIPTION
**Pull request by jiridanek**
Moving changes for https://issues.redhat.com/browse/RHOAIENG-7610 into a rhoai nightly, so they can be tested.

## Description

Began by trying to run GHA, but got error

* https://github.com/opendatahub-io/kubeflow/actions/runs/12393116455/job/34593704662#step:4:56

```
remote: error: GH006: Protected branch update failed for refs/heads/v1.9-branch.        
remote: 
remote: - 4 of 4 required status checks are expected.        
To https://github.com/opendatahub-io/kubeflow
 ! [remote rejected]   v1.9-branch -> v1.9-branch (protected branch hook declined)
error: failed to push some refs to 'https://github.com/opendatahub-io/kubeflow'
```

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
But why still get this protection issue.... I can not understand, theoretically we fixed here.... https://github.com/openshift/release/pull/59443

**Comment by atheo89** [comment]
Next time when you do the sync use this pipilene please: https://github.com/opendatahub-io/kubeflow/actions/workflows/kubeflow-release.yaml 
and select `sync`

**Comment by jiridanek** [comment]
There's OCP-CI outage, apparently

```
level=error msg=Error: Error waiting to create Router: Error waiting for Creating Router: Quota 'ROUTERS' exceeded.  Limit: 20.0 globally.
level=error msg=	metric name = compute.googleapis.com/routers
level=error msg=	limit name = ROUTERS-per-project
level=error msg=	dimensions = map[global:global]
```

/lgtm

**Comment by atheo89** [comment]
> But why still get this protection issue.... I can not understand, theoretically we fixed here.... [openshift/release#59443](https://github.com/openshift/release/pull/59443)

The mystery resolved: The issue was that we set the protection to 'false,' but we never unchecked the option 'Require status checks to pass before merging` from github. https://redhat-internal.slack.com/archives/CBN38N3MW/p1734528043715489

**Pull request merged**
