### PR TITLE
[NO-JIRA] Allow approvers from OWNERS file to run sync gha

### PR DESCRIPTION
**Pull request by atheo89**
This upgrade allow approvers from OWNERS file to run sync gha

## How Has This Been Tested?
https://github.com/atheo89/test-auth-users/actions/runs/11382115618/job/31664947802#step:3:23 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jiridanek** [comment]
Wow, thanks for the thought!

I can't trigger the GHA with the button on https://github.com/opendatahub-io/kubeflow/actions/workflows/sync-branches-through-pr.yaml

Screenshot 2024-10-17 at 12 15 47 PM

How does the PR help with that?

**Comment by jiridanek** [comment]
Furthermore, if the https://github.com/opendatahub-io/kubeflow/actions/workflows/notebook-controller-images-updater.yaml action ran before on both main and v1.9-branch, then there will always be a merge conflict and the sync action will not finish cleanly.

But that's something that can be resolved by adding few sed commands to

https://github.com/opendatahub-io/kubeflow/blob/c3d9c8b349bab85238f30772512f9d4e94803192/.github/workflows/sync-branches-through-pr.yaml#L27

so that's not a problem for now.

**Comment by atheo89** [comment]
>I can't trigger the GHA with the button on 

:woman_facepalming: no idea. 
FYI if you add people as `collaborators`, you can hit that button. Now in this case you are in a team that is called `Notebook Devs`. I guessed that you have the super power to hit that button.. Maybe we need to dive into the settings. 

>action ran before on both main and v1.9-branch, then there will always be a merge conflict and the sync action will not finish cleanly. 

That is true, we should care also

**Comment by jiridanek** [comment]
Still no powers, as far as I can see.

If I understand this PR correctly, I'd title it "Prevent people not in OWNERS file to run sync gha"; it's not about giving access, but about restricting access, looks to me

**Comment by atheo89** [comment]
This won't work since the `Notebook Devs` team has `triage` rights, for this actions needs `write`. 
Closing this, maybe we will found another way.

**Pull request closed without merging**
