### PR TITLE
RHOAIENG-15748: chore(release): set the main tag to `main`, so we need not update it with digest updater from now on

### PR DESCRIPTION
**Pull request by jiridanek**
https://issues.redhat.com/browse/RHOAIENG-15748

Follow-up to

* https://github.com/red-hat-data-services/rhods-devops-infra/pull/131

## Description

image

https://docs.google.com/document/d/1R1zPFKI4-HQY9SeJYa2erSnzr5YNdEU497CdOgni7AY/edit?tab=t.0#heading=h.p8a8iq2tou22

## How Has This Been Tested?

Images with `main` tag are present and can be used

```
podman pull --platform=linux/amd64 quay.io/opendatahub/kubeflow-notebook-controller:main
Trying to pull quay.io/opendatahub/kubeflow-notebook-controller:main...
Getting image source signatures
Copying blob sha256:bb4c96ca6d403d756b0d1fa420b6ade5ab46035a46451db44f1abff5b200b345
Copying blob sha256:e0348fdb2685077d22116d294a90a253709aba78815882a57fcc536b22dcae2f
Copying config sha256:dfab4f088ac5d5587543216d61a0969a63a0c0f148c8a9782b2be221eaf28f6b
Writing manifest to image destination
dfab4f088ac5d5587543216d61a0969a63a0c0f148c8a9782b2be221eaf28f6b
```

```
podman pull --platform=linux/amd64 quay.io/opendatahub/odh-notebook-controller:main
Trying to pull quay.io/opendatahub/odh-notebook-controller:main...
Getting image source signatures
Copying blob sha256:84f1c1f659dd19766fea787ec33bcf66ff5ad1b78be4f6f7eaf73276ee0466e3
Copying blob sha256:e0348fdb2685077d22116d294a90a253709aba78815882a57fcc536b22dcae2f
Copying config sha256:d7ca01df108e912016aa9ce24d9013fd01a1ab323e7674939d3c2451a6cea92a
Writing manifest to image destination
d7ca01df108e912016aa9ce24d9013fd01a1ab323e7674939d3c2451a6cea92a
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jstourac — COMMENTED** [review]
/lgtm

**Comment by jiridanek** [comment]
* https://github.com/opendatahub-io/kubeflow/pull/433

/override ci/prow/odh-notebook-controller-e2e

**Pull request merged**
