### PR TITLE
chore(owners): add `andyatmiami` as reviewer and approver

### PR DESCRIPTION
**Pull request by andyatmiami**
## Description
Adding my own GH handle (`andyatmiami`) to the `approvers` and `reviewers` section of `OWNERS` so I can be more self-sufficient in working issues alongside the team.

## How Has This Been Tested?
no testing required

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Welcome to the OWNERS side! Could you only add your name with alphabetical order?

**Comment by jiridanek** [comment]
The masses stand up to be the OWNERS https://www.youtube.com/clip/UgkxufSgqjTLFtmQsynyICWWqHgjcDEzScsJ

**Review by jiridanek — CHANGES_REQUESTED** [review]
alphabetical order would be good

**Review by jstourac — COMMENTED** [review]
/lgtm

**Comment by jiridanek** [comment]
>Once this PR has been reviewed and has the lgtm label, please ask for approval from [jiridanek](https://github.com/jiridanek). For more information see [the Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

allright, then
/approve

**Comment by jiridanek** [comment]
/honk

honking goose

**Pull request merged**
