### PR TITLE
Add git to quay tag mirroring action

### LINKED ISSUE #44: Add GitHub Action to mirror git tags to quay tags
/kind feature

**Why you need this feature:**
 It would be helpful to set up a similar system as in other odh repositories where each git tagsis mirrored into a quay tag of the same name for easier access.

**Describe the solution you'd like:**
Add a github action that uses skopeo to copy the git tag name into a new quay tag containing the same image.

### PR DESCRIPTION
**Pull request by maroroman**
Resolves #44 

## Description
This PR adds essentially a copy of this PR: https://github.com/opendatahub-io/odh-dashboard/pull/796
but modified to make changes to the odh-notebook-controller quay repo and using a different robot account (should there be multiple?)

This PR requires the following secrets to be added to this repo:
QUAY_ODH_NOTEBOOK_CONTROLLER_IMAGE_REPO
QUAY_ROBOT_TOKEN
QUAY_ROBOT_USERNAME

## How Has This Been Tested?
Tested in the same way as the PR mentioned above

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by maroroman** [comment]
Started in the wrong branch and rebased, not sure if this will show up in commit history, so I can recreate the PR if needed.

**Comment by maroroman** [comment]
Need to rewrite parts based on feedback on a related issue

/hold

**Comment by VaishnaviHire** [comment]
@maroroman This PR needs a rebase

**Comment by maroroman** [comment]
Recreated as #67 to resolve base issues.

**Pull request closed without merging**
