### PR TITLE
chore: add GitHub action for ODH Notebook Controller unit tests

### PR DESCRIPTION
**Pull request by jiridanek**
## Description
This commit introduces a new GitHub action workflow specifically for running unit tests against the ODH Notebook Controller. It's configured to run on both push and pull requests events, ensuring that all code changes are thoroughly tested.

## How Has This Been Tested?
* https://github.com/jiridanek/kubeflow/actions

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jstourac — APPROVED** [review]

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

:+1:

**Pull request merged**
