### PR TITLE
Sync v1.9 branch from main to get the latest changes ready for rhoai-nightly

### PR DESCRIPTION
**Pull request by jiridanek**
```
git switch -c jd_sync_v1.9-branch_from_main origin/v1.9-branch
git pull --rebase=false origin main
# ... hack hack hack ...
cd components/odh-notebook-controller; make manifests
cd components/notebook-controller; make manifests
git merge --continue
git push fork HEAD
```

### CODE REVIEW

**Comment by jiridanek** [comment]
When this is in, I'd want to create sync

https://github.com/red-hat-data-services/kubeflow/compare/master...opendatahub-io:kubeflow:v1.9-branch

**Comment by jiridanek** [comment]
Looks correct to me,  so I'll push it onwards

/approve

it does not include the oauth-proxy revert yet as that was merged after I started the sync, so I'll do another sync right after.

**Comment by jiridanek** [comment]
/override ci/prow/odh-notebook-controller-e2e

no need to retest that, just merge!

**Comment by harshad16** [comment]
@jiridanek , why was this PR required from fork and made same as  this PR https://github.com/opendatahub-io/kubeflow/pull/422 from main ?

**Comment by jiridanek** [comment]
Because we have digest updater running on both main and v1.9-bramch. When the updater does updates on both branches, there will then be a conflict that needs to be resolved by hand. So automatic merge is failing.

When did the sync again with the newly landed PR, updater did not run in the meantime, so there were no conflicts, so I could do it straight in GitHub, without going through intermediate branch.

I could not use the sync haha from @atheo89 because only repo admins have permissions to trigger ghas by clicking button.

**Comment by atheo89** [comment]
Opened this PR to avoid this triggering issues in the future: https://github.com/opendatahub-io/kubeflow/pull/423 
This allow the IDs from the `approvers` list on the OWNERS file to trigger the sync action.
ofc in case of conflicts we should create a handmade pr

**Pull request merged**
