### PR TITLE
cherry-pick from master most recent notebook controller commits for v1.6-branch

### PR DESCRIPTION
**Pull request by shalberd**
The v1.6 branch is behind certain necessary commits when it comes to notebook controller logic.
## Description

cherry-picked commits from master branch
311b79c fix notebook culling
d8e8f91 update notebook status properly
806d32b mirroring pod conditions to notebook
fc09bd1 fix notebook endless restarts

Looks like I cherry-picked the commit for "Mirroring Pod conditions to Notebook" twice and commited twice. [There is no difference between those two commits ](https://github.com/shalberd/kubeflow/compare/9ce7f7286ef9b101089353df88dd74a0d25de86b...fe05ee494d407aa3e1d2b358ec12a2cd250d54ec)(see Commits tab) 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
@shalberd Instead of cherry-picking, I think we want to rebase this branch with v1.6.0 release tag. This can be done using following command
```
git pull <kubeflow-remote-name> refs/tags/v1.6.0 --rebase
```

Note: We would need to resolve the merge conflicts as well.

**Comment by shalberd** [comment]
> @shalberd Instead of cherry-picking, I think we want to rebase this branch with v1.6.0 release tag. This can be done using following command
> 
> ```
> git pull <kubeflow-remote-name> refs/tags/v1.6.0 --rebase
> ```
> 
> Note: We would need to resolve the merge conflicts as well.

By rebasing based on a tag, I assume you mean the tag in kubeflow/kubeflow, not opendatahub-io/kubeflow, correct? Because the tag v1.6.0 is not present in opendatahub-io/kubeflow. Also, with regards to v1.6-branch of kubeflow/kubeflow upstream, there is a more recent tag, v1.6.1.

In essence, you are proposing not to cherry-pick from our master, but instead to take kubeflow/kubeflow with tag v.1.6.0 (or 1.6.1, as I suggested) as the basis for dropping in the changes to our opendatahub-io/kubeflow v1.6-branch, am I understanding correctly?

So the idea is to take all files and commits related to v1.6.1 ref upstream at kubeflow/kubeflow and properly align the upstream commits onto our v1.6.0-branch commit history, but without crushing/squashing the commits, correct?

`git pull <kubeflow-remote-name> refs/tags/v1.6.1 --rebase`

I don't quite get what to refer to here. I am on my local branch kubeflow/kubeflow v1.6.0-branch, what are you proposing?

**Comment by VaishnaviHire** [comment]
> > @shalberd Instead of cherry-picking, I think we want to rebase this branch with v1.6.0 release tag. This can be done using following command
> > ```
> > git pull <kubeflow-remote-name> refs/tags/v1.6.0 --rebase
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note: We would need to resolve the merge conflicts as well.
> 
> By rebasing based on a tag, I assume you mean the tag in kubeflow/kubeflow, not opendatahub-io/kubeflow, correct? Because the tag v1.6.0 is not present in opendatahub-io/kubeflow. Also, with regards to v1.6-branch of kubeflow/kubeflow upstream, there is a more recent tag, v1.6.1.
> 
> In essence, you are proposing not to cherry-pick from our master, but instead to take kubeflow/kubeflow with tag v.1.6.0 (or 1.6.1, as I suggested) as the basis for dropping in the changes to our opendatahub-io/kubeflow v1.6-branch, am I understanding correctly? 
> 

Yes that is correct,  add `kubeflow/kubeflow` as remote, and rebase the branch with v1.6.1 tag.

> So the idea is to take all files and commits related to v1.6.1 ref upstream at kubeflow/kubeflow and properly align the upstream commits onto our v1.6.0-branch commit history, but without crushing/squashing the commits, correct?
> 
> `git pull <kubeflow-remote-name> refs/tags/v1.6.1 --rebase`
> 
> I don't quite get what to refer to here. I am on my local branch kubeflow/kubeflow v1.6.0-branch, what are you proposing?

This would be the remote name for `https://github.com/kubeflow/kubeflow.git `. You can find it by using `git remote -v`

**Comment by shalberd** [comment]
Yup, e.g. in my case, having cloned opendatahub-io and being on the v1.6-branch, I was able to add the new upstream remote

`git remote add odhupstream https://github.com/kubeflow/kubeflow.git`

then rebasing locally-checked-out branch with the command

`git pull odhupstream refs/tags/v1.6.1 --rebase`

```
 git branch 
* (no branch, rebasing v1.6-branch)
  v1.6-branch
```

Commencing with Github Desktop and a good editor now, only 19 conflicted files :-)

Thank you for your explanations, they really helped get the idea across. I will open the new PR as soon as the changes are ready.

**Comment by shalberd** [comment]
New PR here

https://github.com/opendatahub-io/kubeflow/pull/68

**Pull request closed without merging**
