### PR TITLE
RHOAIENG-9824: gha(odh-nbc): improve the GitHub Actions integration test for odh-notebook-controller to start the controller successfully and run a notebook

### PR DESCRIPTION
**Pull request by jiridanek**
https://issues.redhat.com/browse/RHOAIENG-9824

## Description
Previously, the test was of a questionable value, because even normally, the operator was unable to initialize itself in upstream kubernetes (kind). Now the initialization is successful and a notebook is started.

## How Has This Been Tested?
Run GHA

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
Also, shouldn't we aim against `main` branch now?

**Comment by jiridanek** [comment]
> Doesn't this need a rebase?

done

> Also, shouldn't we aim against main branch now?

dunno, I changed the PR target to main

**Pull request merged**
