### PR TITLE
rebased v1.6-branch with v1.6.1 release tag upstream

### PR DESCRIPTION
**Pull request by shalberd**
Our v1.6 branch was not up to date with the upstream branch v1.6 and release tag v1.6.1
I did a
`git remote add odhupstream https://github.com/kubeflow/kubeflow.git`
and then rebased our branch / the local branch based on release tag v1.6.1 upstream.
`git pull odhupstream refs/tags/v1.6.1 --rebase`

I did not squash commits, the commits seem good as they are in terms of granularity.

## Description

As a result, several merge conflicts occured, which was to be expected and which I resolved with a mix of the GUI applications Github Desktop and a souped-up text editor on my laptop. In general, I always went with what was included upstream when resolving merge conflicts. I read through the PRs upstream and the reasonings made sense to me.

General observations and how I proceeded with merge conflicts:
1) Some Github workflows changes and makefiles changes, all seem straight-forward

  Their aim was to enable workflows on version changes of components, it seems.
  e.g. pushing images via their Makefile on Version change

  1.1) github/workflows/all_components_docker_publish.yaml  file does not exist on target branch

        (Build and Push all Kubeflow images)
        decided to not include it anymore as it was removed as part of upstream PR 

https://github.com/kubeflow/kubeflow/pull/6597 on July 26, 2022

  1.2) It seems that workflows in general were changed from only make docker-build to in addition make docker-push, explaining the deleted publish file here. github/workflows/nb_server_docker_publish.yaml  file does not exist on target branch

        (Build all Notebook Server images via central-Makefile)
        decided to not include it anymore as it was removed as part of upstream PR 

https://github.com/kubeflow/kubeflow/pull/6591 on July 25, 2022. now environment-specific nb-server workflows, e.g. nb-server-jupyter-scipy and so on

  1.3) in general, there are new sections in the workflows to do a push of a new component image on version change.
         e.g.

    ```
      - name: Run KFAM push on Version change
        id: version
        if: github.event_name == 'push' && steps.filter.outputs.version == 'true'
        run: |
          export TAG=$(cat releasing/version/VERSION)
          cd components/access-management
          export IMG=kubeflownotebookswg/kfam
          make docker-build
          make docker-push
    ```

2) some other noteworthy change I saw, **unsure if we even use profile-controller**. I guess not, I mean, even before this change, there is a kubectl apply (instead of oc apply -f) in components/profile-controller/Makefile
 
    Support K8s 1.22 in profile controller

    https://github.com/opendatahub-io/kubeflow/commit/5e09536fd36cf8265d76730de4cbbd5c6140b28e#diff-4e187004d8bc8265014b3086e2324d5a913bba48a20736dfc8a1dcb5d37d6461

     now using **envtest binary (**# ENVTEST_K8S_VERSION refers to the version of kubebuilder assets to be downloaded by envtest binary)

     **Q: for our purposes, what is envtest binary and can we use it, too? I guess so ...** 

3) golang version removed 1.15, new 1.17, but defined elsewhere directly / hard-coded in Dockerfile(s) instead of by variable

4) components/profile-controller/config/samples/_v1_profile_aws_iam.yaml 
    did not exist on our branch, was added as part of PR https://github.com/kubeflow/kubeflow/pull/6624/files#diff-0cb297df3d35d1686365c5731025bc07fcbd4ea8fe385e8b4cf67ba80b1cff14, so I added it, too.

5) They are using dockerhub for all images now. https://github.com/kubeflow/kubeflow/pull/6548

**Is building and publishing all docker images to Docker Hob ok with you**? In my fork here, the step "Build and Push Docker image to Docker Hub" failed"with the message: "username and password required" when I pushed the commits.  But, that is probably due to some Github config not being correct in my Github username. Related to

```
- name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
```

6) Cool, there is now also a notebook controller unit test https://github.com/kubeflow/kubeflow/pull/6628/files#diff-0defb33d3c0f4c4983fd923b8ad8d34bb4107a0795f69eb602bdf0ddcc9dbc8e

I resolved all conflicts and at the end, force-pushed to rewrite the history after rebase.
The result is in this PR

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by shalberd** [comment]
good, ci/prow tests all ran through successfully. On first run of e2e test, there seemed to have been a resource-problem with the CI framework.

**Comment by VaishnaviHire** [comment]
Thanks @shalberd for the PR. This looks good, we will test the changes with latest ODH manifests

**Comment by shalberd** [comment]
during rebase, not including all-components-docker-publish github workflow was included by accident, I changed this with a commit

**Review by VaishnaviHire — COMMENTED** [review]
Thank you for the PR ! The changes worked for me on 4.12 OpenShift cluster

/lgtm

**Pull request merged**
