### PR TITLE
feat: disables features not needed for Istio deployments

### LINKED ISSUE #168: v1.7 branch is missing Service Mesh logic for handling notebooks
/kind bug

Changes brought in #96 are present in `v1.6` branch but not in the currently active `v1.7` development branch. This makes it impossible to test Service Mesh integration using newer images.

### PR DESCRIPTION
**Pull request by bartoszmajsak**
## Description

Brings back #96 (see description of it for more details).

Additional changes brought from (now closed) #184

- changed the overlays set-up for `kf-notebook-controller` here to have an `overlays/standalone-service-mesh` used solely for e2e testing for notebook controllers, and use `overlays/service-mesh` for when deploying through ODH operator.
- in addition we removed the `overlays/service-mesh` for the odh-notebook-controller as we will no longer need to patch the image once this is merged.

Fixes #168

## How Has This Been Tested?

```
export K8S_NAMESPACE=opendatahub
kubectl create ns $K8S_NAMESPACE
make deploy-service-mesh
make deploy-with-mesh -e IMG=quay.io/maistra-dev/odh-notebook-controller -e TAG=v1.7-service-mesh
make e2e-test-service-mesh
make undeploy-with-mesh
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@VaishnaviHire @harshad16 I would very much appreciate a review and merge so I can test Service Mesh changes against the latest versions of the controllers.

**Comment by bartoszmajsak** [comment]
The `kustomize` overlay provided in this PR is used for e2e tests only. We are working on porting our changes done for `odh-manifests` repo for operator v2 work and will provide them as a separate PR.

**Comment by harshad16** [comment]
Working on reviewing this PR.

**Comment by bartoszmajsak** [comment]
> The `kustomize` overlay provided in this PR is used for e2e tests only. We are working on porting our changes done for `odh-manifests` repo for operator v2 work and will provide them as a separate PR.

@harshad16 to simplify the review/merge @cam-garrison brought #184 changes here. All ready for review.

**Review by harshad16 — COMMENTED** [review]
Apologies for the delay in review.
While testing the deployment:
getting the mutate-webook error
```
make e2e-test-service-mesh -e K8S_NAMESPACE=opendatahub
go test ./e2e/ -run ^TestE2ENotebookController -v \
	--nb-namespace=opendatahub \
	--deploymentMode=service-mesh \
	"--skip-deletion=false" 
=== RUN   TestE2ENotebookController
=== RUN   TestE2ENotebookController/validate_controllers
I1017 01:57:15.802869   75749 request.go:601] Waited for 1.047326253s due to client-side throttling, not priority and fairness, request: GET:https://api.hnalla.dev.datahub.redhat.com:6443/apis/datasciencecluster.opendatahub.io/v1?timeout=32s
=== RUN   TestE2ENotebookController/validate_controllers/Validate_Kubeflow_notebook_controller
=== RUN   TestE2ENotebookController/validate_controllers/Validate_ODH_notebook_controller
=== RUN   TestE2ENotebookController/create
I1017 01:57:41.221572   75749 request.go:601] Waited for 1.046904354s due to client-side throttling, not priority and fairness, request: GET:https://api.hnalla.dev.datahub.redhat.com:6443/apis/extensions.istio.io/v1alpha1?timeout=32s
=== RUN   TestE2ENotebookController/create/thoth-minimal-service-mesh-notebook
=== RUN   TestE2ENotebookController/create/thoth-minimal-service-mesh-notebook/Creation_of_Notebook_instance
2023/10/17 01:58:04 Error creating Notebook resource thoth-minimal-service-mesh-notebook: Internal error occurred: failed calling webhook "notebooks.opendatahub.io": failed to call webhook: Post "https://odh-notebook-controller-webhook-service.opendatahub.svc:443/mutate-notebook-v1?timeout=10s": context deadline exceeded, trying again
2023/10/17 01:58:24 Error creating Notebook resource thoth-minimal-service-mesh-notebook: Internal error occurred: failed calling webhook "notebooks.opendatahub.io": failed to call webhook: Post "https://odh-notebook-controller-webhook-service.opendatahub.svc:443/mutate-notebook-v1?timeout=10s": context deadline exceeded, trying again
```

**Comment by harshad16** [comment]
Seems like something similar was addressed here: https://github.com/opendatahub-io/kubeflow/pull/96#issuecomment-1591291961

**Comment by cam-garrison** [comment]
> Apologies for the delay in review. While testing the deployment: getting the mutate-webook error
> 
> ```
> make e2e-test-service-mesh -e K8S_NAMESPACE=opendatahub
> go test ./e2e/ -run ^TestE2ENotebookController -v \
> 	--nb-namespace=opendatahub \
> 	--deploymentMode=service-mesh \
> 	"--skip-deletion=false" 
> === RUN   TestE2ENotebookController
> === RUN   TestE2ENotebookController/validate_controllers
> I1017 01:57:15.802869   75749 request.go:601] Waited for 1.047326253s due to client-side throttling, not priority and fairness, request: GET:https://api.hnalla.dev.datahub.redhat.com:6443/apis/datasciencecluster.opendatahub.io/v1?timeout=32s
> === RUN   TestE2ENotebookController/validate_controllers/Validate_Kubeflow_notebook_controller
> === RUN   TestE2ENotebookController/validate_controllers/Validate_ODH_notebook_controller
> === RUN   TestE2ENotebookController/create
> I1017 01:57:41.221572   75749 request.go:601] Waited for 1.046904354s due to client-side throttling, not priority and fairness, request: GET:https://api.hnalla.dev.datahub.redhat.com:6443/apis/extensions.istio.io/v1alpha1?timeout=32s
> === RUN   TestE2ENotebookController/create/thoth-minimal-service-mesh-notebook
> === RUN   TestE2ENotebookController/create/thoth-minimal-service-mesh-notebook/Creation_of_Notebook_instance
> 2023/10/17 01:58:04 Error creating Notebook resource thoth-minimal-service-mesh-notebook: Internal error occurred: failed calling webhook "notebooks.opendatahub.io": failed to call webhook: Post "https://odh-notebook-controller-webhook-service.opendatahub.svc:443/mutate-notebook-v1?timeout=10s": context deadline exceeded, trying again
> 2023/10/17 01:58:24 Error creating Notebook resource thoth-minimal-service-mesh-notebook: Internal error occurred: failed calling webhook "notebooks.opendatahub.io": failed to call webhook: Post "https://odh-notebook-controller-webhook-service.opendatahub.svc:443/mutate-notebook-v1?timeout=10s": context deadline exceeded, trying again
> ```

The latest Service Mesh SMCP v2.3 (2.3.7) release has failures as it was released with an outdated image. This is likely the root of the issues you're facing since the install script installs v2.3 smcp. The fix for v2.3 SMCPs is coming ASAP, but as of now, newly created or updated SMCPs of this version are buggy.

I ran the tests again after changing the SMCP to be v2.4 and the tests succeeded. Please give that a try when you can.

**Comment by bartoszmajsak** [comment]
@cam-garrison can we adjust the script to use 2.4 instead?

**Comment by bartoszmajsak** [comment]
@harshad16 besides test failures - is the code looking good for you?

**Comment by harshad16** [comment]
yes, it does look good to me :100:

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

We just need to fix servicemesh issue with the webhook
which we would address slowly.
Thanks for the patience

**Comment by shalberd** [comment]
tests succeeded

**Comment by shalberd** [comment]
Thanks goes to @harshad16 he did the heavy lifting

**Pull request merged**
