### PR TITLE
NO-JIRA: chore(nbcs): update tooling in controller's Makefiles

### PR DESCRIPTION
**Pull request by jiridanek**
Look at this first, after this gets in, the diff will shrink

* https://github.com/opendatahub-io/kubeflow/pull/392

## Description

Update tooling in notebook controller Makefile,

* controller-gen
* kustomize
* setup-envtest

This is motivated by first the fact that old controller-gen segfaults on my machine, and that old setup-envtest does not run on macOS. Kustomize is updated to align with https://issues.redhat.com/browse/RHOAIENG-11679 and

* https://github.com/opendatahub-io/notebooks/pull/682

## How Has This Been Tested?

- Github Actions
- `make test`, `make manifests`, `make generate` locally

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
/hold

Hey Jiri, could you switch the target branch to main please?

**Comment by jiridanek** [comment]
Sure, rebased, retargetted.

**Review by jstourac — COMMENTED** [review]
/lgtm

**Comment by jiridanek** [comment]
rebased
/approve

**Pull request merged**
