### PR TITLE
NO-JIRA: chore(nbcs): run `make generate` in `components/notebook-controller` to update the yamls

### PR DESCRIPTION
**Pull request by jiridanek**
Run `make generate` in the project directory, commit the result

## Description

It appears that this was not run in a while and therefore the code got out of sync with the generated yamls.

## How Has This Been Tested?

- Github Actions

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jstourac** [comment]
/lgtm

Should we consider to run this periodically somehow? :thinking:

**Comment by jiridanek** [comment]
> Should we consider to run this periodically somehow? 🤔

There should be a CI check that will fail if manifests are out-of-date, ideally. This is something that a go developer is supposed to run before a commit. Could be a pre-commit check, also.

**Comment by atheo89** [comment]
/hold 

Hey Jiri, could you switch the target branch to `main` please?

**Comment by jiridanek** [comment]
Rebased, I'll go test it now.

**Comment by jiridanek** [comment]
I checked that on `https://console-openshift-console.apps.ods-qe-psi-06` cluster, the basic nbc functionality still works, I can spawn notebooks from dashboard without problems. I had issue with oauth proxy because we still don't have the ocp 4.16 fips compatible oauth proxy in downstream manifests, so I had to update the oauth-proxy by hand first before I was able to connect to the notebook.

/unhold
/approve

**Comment by atheo89** [comment]
I’m holding off because main is now the default branch, and all pull requests will target it. We won’t be doing cherry-picks anymore unless there’s a specific reason to hold something on main. Periodically, we’ll sync the changes to v1.9 using GitHub Actions.

@harshad16, I’m not sure if using [cherrypick main](https://github.com/opendatahub-io/kubeflow/pull/392#issuecomment-2387990233) might cause any issues with the git commit history. If it won’t, then I’m okay with proceeding.

**Comment by atheo89** [comment]
Here is a PR that introduce on the repo this sync https://github.com/opendatahub-io/kubeflow/pull/404 among the branches. No cherry-picks anymore :slightly_smiling_face:

**Comment by harshad16** [comment]
>I’m not sure if using https://github.com/opendatahub-io/kubeflow/pull/392#issuecomment-2387990233 might cause any issues with the git commit history. If it won’t, then I’m okay with proceeding.

i think , we can merge, it would cause now additional commits for same change, when we sync v1.9-branch with main. anyhow now that this PR is already merged ,it would be okay to do so.
and lets in future, focus on default PR to main and only Patch PRs to v1.9-branch.

**Pull request merged**
